{% set version = "4.2.7" %}

package:
  name: irods
  version: "{{ version }}"

about:
  home: https://irods.org
  license: BSD
  summary: "Open Source Data Management Software."

build:
  number: 0

source:
  git_url: https://github.com/irods/irods.git
  git_rev: {{ version }}
  patches:
    - 0001-Work-around-compiler-bug-in-GCC-7.3.0.patch

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - autoconf
    - automake
    - cmake
    - libtool
    - make
    - perl
    - pkg-config
  host:
    - avro==1.7.7
    - aws-sdk-cpp==1.4.92
    - boost==1.60.0
    - catch2==2.6.1
    - cppzmq==4.2.1
    - jansson==2.7
    - libarchive==3.3.2
    - zeromq==4.2.1
    - openssl
    - unixodbc
    - psqlodbc
    - libpam-dev
  run:
    - avro==1.7.7
    - aws-sdk-cpp==1.4.92
    - boost==1.60.0
    - catch2==2.6.1
    - cppzmq==4.2.1
    - jansson==2.7
    - libarchive==3.3.2
    - zeromq==4.2.1
    - openssl
    - unixodbc
    - psqlodbc
    - libpam
